logging:
    level:
        root: WARN
        fr.kuremento.dnd: DEBUG
        org.springframework.context.support: ERROR

spring:
    application:
        name: '@project.name@'
    jpa:
        hibernate:
            ddl-auto: none
    main:
        allow-bean-definition-overriding: true
    shell:
        noninteractive:
            primary-command: convert

server:
    port: 8080

application:
    file:
        input-empty-file: "classpath:data/input.pdf"
    version: '@project.version@'