logging:
    level:
        root: WARN
        fr.kuremento.dnd: DEBUG
        org.springframework.context.support: ERROR
    pattern:
        console:

spring:
    application:
        name: '@project.name@'
    main:
        allow-bean-definition-overriding: true
server:
    port: 8080

application:
    version: '@project.version@'