logging:
    level:
        root: WARN
        fr.kuremento.dnd: DEBUG
    pattern:
        console:

spring:
    application:
        name: '@project.name@'
    main:
        allow-bean-definition-overriding: true
        banner-mode: off

server:
    port: 8080

application:
    name: '@project.name@'
    version: '@project.version@'