CREATE SCHEMA IF NOT EXISTS DND;
DROP TABLE IF EXISTS DND.MAPPING;
CREATE TABLE IF NOT EXISTS DND.MAPPING
(
    ENGLISH_CATEGORY CHARACTER VARYING not null,
    FRENCH_CATEGORY  CHARACTER VARYING not null,
    IS_CHECK_BOX  BOOLEAN not null DEFAULT FALSE,
    constraint MAPPING_PK primary key (ENGLISH_CATEGORY, FRENCH_CATEGORY)
);

-- Général
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('CharacterName', 'CharacterName');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('CharacterName', 'CharacterName 2');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('CLASS  LEVEL', 'ClassLevel');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('BACKGROUND', 'Background');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('PLAYER NAME', 'PlayerName');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('EXPERIENCE POINTS', 'XP');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('RACE', 'Race');

-- Statistiques et jets de sauvegarde
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('CHamod', 'CHAmod');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('StrProf', 'MaîtriseForce', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('DexProf', 'MaîtriseDextérité', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('ConProf', 'MaîtriseConstitution', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('IntProf', 'MaîtriseIntelligence', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('WisProf', 'MaîtriseSagesse', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('ChaProf', 'MaîtriseCharisme', true);

-- Compétences
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('AcrobaticsProf', 'MaîtriseAcrobaties', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Acrobatics', 'Acrobaties');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('ArcanaProf', 'MaîtriseArcanes', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Arcana', 'Arcanes');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('AthleticsProf', 'MaîtriseAthlétisme', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Athletics', 'Athlétisme');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('StealthProf', 'MaîtriseDiscrétion', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Stealth ', 'Discrétion');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('AnimalHandlingProf', 'MaîtriseDressage', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Animal', 'Dressage');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('SleightOfHandProf', 'MaîtriseEscamotage', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('SleightofHand', 'Escamotage');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('HistoryProf', 'MaîtriseHistoire', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('History', 'Histoire');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('IntimidationProf', 'MaîtriseIntimidation', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Intimidation', 'Intimidation');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('InvestigationProf', 'MaîtriseInvestigation', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Investigation', 'Investigation');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('MedicineProf', 'MaîtriseMédecine', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Medicine', 'Médecine');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('NatureProf', 'MaîtriseNature', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Nature', 'Nature');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('PerceptionProf', 'MaîtrisePerception', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Perception', 'Perception');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('InsightProf', 'MaîtrisePerspicacité', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Insight', 'Perspicacité');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('PersuasionProf', 'MaîtrisePersuasion', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Persuasion', 'Persuasion');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('ReligionProf', 'MaîtriseReligion', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Religion', 'Religion');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('PerformanceProf', 'MaîtriseReprésentation', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Performance', 'Représentation');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('SurvivalProf', 'MaîtriseSurvie', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Survival', 'Survie');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('DeceptionProf', 'MaîtriseTromperie', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Deception', 'Tromperie');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('CustomProf1', 'CustomProf1', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('CustomProf2', 'CustomProf2', true);
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY, IS_CHECK_BOX) VALUES ('CustomProf3', 'CustomProf3', true);

-- Maîtrises
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Passive1', 'PerceptionPassive');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Passive2', 'PerspicacitéPassive');
INSERT INTO DND.MAPPING (ENGLISH_CATEGORY, FRENCH_CATEGORY) VALUES ('Passive3', 'InvestigationPassive');