CREATE SCHEMA IF NOT EXISTS DND;
DROP TABLE IF EXISTS DND.MAPPING;
CREATE TABLE IF NOT EXISTS DND.MAPPING
(
    MAPPING_ID       INT AUTO_INCREMENT PRIMARY KEY,
    FROM_CATEGORY CHARACTER VARYING not null,
    TO_CATEGORY  CHARACTER VARYING not null,
    IS_CHECK_BOX     BOOLEAN           not null DEFAULT FALSE,
    constraint MAPPING_UNIQUE UNIQUE (FROM_CATEGORY, TO_CATEGORY)
);

-- General
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('CharacterName', 'CharacterName1');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('CharacterName', 'CharacterName2');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('CharacterName', 'CharacterName3');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('CharacterName', 'CharacterName4');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('CLASS  LEVEL', 'XP1');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('CLASS  LEVEL', 'XP2');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('CLASS  LEVEL', 'XP3');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('CLASS  LEVEL', 'XP4');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('BACKGROUND', 'Background1');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('BACKGROUND', 'Background2');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('BACKGROUND', 'Background3');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('BACKGROUND', 'Background4');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('RACE', 'Race1');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('RACE', 'Race2');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('RACE', 'Race3');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('RACE', 'Race4');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('ALIGNMENT', 'Alignment1');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('ALIGNMENT', 'Alignment2');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('ALIGNMENT', 'Alignment3');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('ALIGNMENT', 'Alignment4');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('Check Box 12', 'STDSuccess1', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('Check Box 13', 'STDSuccess2', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('Check Box 14', 'STDSuccess3', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('Check Box 15', 'STDFailure1', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('Check Box 16', 'STDFailure2', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('Check Box 17', 'STDFailure3', true);

-- Statistiques et jets de sauvegarde
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('CHamod', 'CHAmod');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('DEXmod ', 'DEXmod');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('StrProf', 'StrProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('DexProf', 'DexProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('ConProf', 'ConProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('IntProf', 'IntProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('WisProf', 'WisProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('ChaProf', 'ChaProf', true);

-- Competences
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('AcrobaticsProf', 'AcrobaticsProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('ArcanaProf', 'ArcanaProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('AthleticsProf', 'AthleticsProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('StealthProf', 'StealthProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('AnimalHandlingProf', 'AnimalHandlingProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('SleightOfHandProf', 'SleightOfHandProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('HistoryProf', 'HistoryProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('IntimidationProf', 'IntimidationProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('InvestigationProf', 'InvestigationProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('MedicineProf', 'MedicineProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('NatureProf', 'NatureProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('PerceptionProf', 'PerceptionProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('InsightProf', 'InsightProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('PersuasionProf', 'PersuasionProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('ReligionProf', 'ReligionProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('PerformanceProf', 'PerformanceProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('SurvivalProf', 'SurvivalProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY, IS_CHECK_BOX) VALUES ('DeceptionProf', 'DeceptionProf', true);
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('Animal', 'AnimalHandling');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('SleightofHand', 'SleightOfHand');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('Stealth ', 'Stealth');

-- Maitrises
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('Passive1', 'PassivePerception');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('spellSaveDC0', 'SpellSaveDC1');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('spellSaveDC0', 'SpellSaveDC4');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('spellCastingAbility0', 'SpellCastingAbility');
INSERT INTO DND.MAPPING (FROM_CATEGORY, TO_CATEGORY) VALUES ('spellAtkBonus0', 'SpellAtkBonus');